// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require("Witnet")
const WitnetBridgeInterface = artifacts.require("WitnetBridgeInterface")
const PriceFeed = artifacts.require("PriceFeed")

module.exports = function (deployer) {
  deployer.link(Witnet, [PriceFeed])
  deployer.deploy(PriceFeed, WitnetBridgeInterface.address)
}
